## Playbook to install Java & Tomcat
---
- name: install tomcat server
  hosts: web

  tasks:
  - name: install java
    yum:
      name: java
      state: latest
  - name: Download tomcat server packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
      dest: /usr/local
  - name: extract tomcat packages
      src: /usr/local/apache-tomcat-8.5.81.tar.gz
      dest: /usr/local
      remote_src: yes
  - name: start tomcat services
    shell: nohup /usr/local/apache-tomcat-8.5.81/bin/startup.sh
