---
- hosts: db
  remote_user: root


  tasks:
    - name: Installing Apache
      yum:
        name: httpd
        state: installed

    - name: Enabling httpd service and start the service
      service:
        name: httpd
        enabled: start
        state: started

    - name: Install MYSQL DB Community edition
      yum:
        name:
          - mariadb-server
          - mariadb
        state: latest

    - name: Start the MYSQL service
      service:
        name: mariadb
        enabled: yes
        state: started


    - name: Installing PHP
      yum:
        name:
          - php
          - php-mysql
        state: latest

     - name: Installing PHP
      yum:
        name:
          - php
          - php-mysql
        state: latest

    - name: Copying your php file in the /var/www/html
      copy:
        src: ./index.php
        dest: /var/www/html/index.php
